const parts=[
  {id:'hood',term:'Hood',ko:'후드',image:'images/venue/front.jpg',where:'차량 앞쪽 상부에서 엔진룸을 덮는 큰 패널입니다.',look:'앞유리 아래에서 전면 조명부까지 이어지는 넓은 금속 패널을 찾으세요.',pins:[[49,32]]},
  {id:'headlamps',term:'Headlamps',ko:'헤드램프',image:'images/venue/front.jpg',where:'차량 전면의 왼쪽과 오른쪽에 한 쌍으로 배치됩니다.',look:'야간에 전방을 비추는 주 조명입니다. 이 VENUE에는 세로형 Quad beam LED headlamps가 적용됩니다.',pins:[[37,46],[62,46]]},
  {id:'tires_wheels',term:'Tires and wheels',ko:'타이어와 휠',image:'images/venue/side.jpg',where:'차량 하부 네 모서리에 장착되며 측면 이미지에서는 앞뒤 한 쌍이 보입니다.',look:'노면과 맞닿는 고무 부분이 타이어이고, 안쪽 금속 구조가 휠입니다.',pins:[[27,64],[72,64]]},
  {id:'mirrors',term:'Outside rearview mirrors',ko:'실외 후방 미러',image:'images/venue/side.jpg',where:'앞문 위쪽, 운전석과 동승석 바깥에 한 쌍으로 장착됩니다.',look:'운전자가 차량 옆과 뒤를 확인하는 외부 미러입니다.',pins:[[43,32]]}
];
const app=document.querySelector('#app'),scoreEl=document.querySelector('#score'),tabs=[...document.querySelectorAll('.tab')];
let mode='learn',learnIndex=Math.min(Number(localStorage.getItem('cm04_learnIndex')||0),3),score=Number(localStorage.getItem('cm04_score')||0),testState=null;
function save(){localStorage.setItem('cm04_learnIndex',learnIndex);localStorage.setItem('cm04_score',score);scoreEl.textContent=score}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pins(p,hide=false){return p.pins.map((x,i)=>`<span class="part-pin ${hide?'quiz-pin':''}" style="left:${x[0]}%;top:${x[1]}%"><i>${i+1}</i></span>`).join('')}
function visual(p,hide=false){return `<div class="visual photo"><span class="visual-label">ALL-NEW VENUE · ${p.image.includes('front')?'FRONT':'SIDE'}</span><img class="real-car" src="${p.image}" alt="올뉴 현대 VENUE ${p.ko} 학습 이미지">${pins(p,hide)}</div>`}
function setMode(next){mode=next;testState=null;tabs.forEach(t=>{const on=t.dataset.mode===mode;t.classList.toggle('active',on);t.setAttribute('aria-pressed',on)});render();app.focus({preventScroll:true})}
tabs.forEach(t=>t.onclick=()=>setMode(t.dataset.mode));document.querySelector('#home').onclick=()=>{learnIndex=0;setMode('learn')};
function renderLearn(){const p=parts[learnIndex];app.innerHTML=`<section class="card learn-grid">${visual(p)}<div class="learn-copy"><div class="step-row"><span class="eyebrow">외장 파트 학습</span><span class="step">${learnIndex+1} / ${parts.length}</span></div><p class="korean-name">${p.ko}</p><h1>${p.term}</h1><div class="facts"><div class="fact"><small>어디에 있나요?</small><p>${p.where}</p></div><div class="fact"><small>무엇을 보면 되나요?</small><p>${p.look}</p></div></div><div class="source-chip">HYUNDAI OFFICIAL TERM</div><div class="progress"><span style="width:${(learnIndex+1)/parts.length*100}%"></span></div><div class="learn-actions"><button class="btn" id="prev" ${learnIndex===0?'disabled':''}>← 이전</button><button class="btn primary" id="next">${learnIndex===3?'4지선다 시작':'숙지했어요 · 다음 →'}</button></div></div></section>`;document.querySelector('#prev').onclick=()=>{learnIndex--;save();renderLearn()};document.querySelector('#next').onclick=()=>{if(learnIndex===3)setMode('test');else{learnIndex++;save();renderLearn()}}}
function makeQuestion(p,type,i){if(type==='test')return{p,prompt:'표시된 자동차 파트의 정확한 영어 명칭은 무엇인가요?',answer:p.term};const variants=[`‘${p.ko}’의 정확한 영어 명칭은 무엇인가요?`,`다음 설명에 해당하는 파트는 무엇인가요? “${p.look}”`,`다음 위치에 있는 파트는 무엇인가요? “${p.where}”`];return{p,prompt:variants[i%3],answer:p.term}}
function startTest(type){const list=type==='mixed'?shuffle([...parts,...parts]):shuffle(parts);testState={type,questions:list.map((p,i)=>({...makeQuestion(p,type,i),options:shuffle(parts.map(x=>x.term))})),index:0,correct:0,answered:false};renderQuestion()}
function renderQuestion(){const s=testState;if(s.index===s.questions.length)return renderResults();const q=s.questions[s.index],showImage=s.type==='test'||s.index%3===0;app.innerHTML=`<section class="card test-card"><div class="test-top"><div><span class="eyebrow">${s.type==='mixed'?'혼합 테스트':'이미지 4지선다'}</span><h1>${s.type==='mixed'?'설명과 이미지를 함께 확인하세요':'파란 표시를 확인하세요'}</h1></div><span class="question-count">${s.index+1} / ${s.questions.length}</span></div><div class="progress"><span style="width:${s.index/s.questions.length*100}%"></span></div>${showImage?visual(q.p,true):''}<div class="question-box"><span class="prompt-label">문제</span><h2>${q.prompt}</h2><div class="answers">${q.options.map(x=>`<button class="answer" data-answer="${esc(x)}">${x}</button>`).join('')}</div><div class="feedback" id="feedback" aria-live="polite">정답을 하나 선택하세요.</div><div class="test-actions"><button class="btn primary" id="continue" hidden>${s.index===s.questions.length-1?'결과 보기':'다음 문제 →'}</button></div></div></section>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b,q));document.querySelector('#continue').onclick=()=>{s.index++;s.answered=false;renderQuestion()}}
function answer(button,q){if(testState.answered)return;testState.answered=true;const ok=button.dataset.answer===q.answer;if(ok){testState.correct++;score+=100}else score=Math.max(0,score-25);save();document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct')});button.classList.add(ok?'correct':'wrong');const f=document.querySelector('#feedback');f.className=`feedback ${ok?'good':'bad'}`;f.innerHTML=ok?`정답입니다. <strong>${q.answer}</strong> · +100점`:`정답은 <strong>${q.answer}</strong>입니다. · −25점`;document.querySelector('#continue').hidden=false}
function rating(p){if(p===100)return['MASTER','모든 파트를 정확히 구분했습니다.'];if(p>=75)return['EXPERT','한 번만 더 복습하면 완벽합니다.'];if(p>=50)return['DRIVER','좋은 시작입니다. 틀린 파트를 다시 확인하세요.'];return['ROOKIE','파트 학습 4개를 다시 본 뒤 재도전하세요.']}
function renderResults(){const s=testState,total=s.questions.length,pct=Math.round(s.correct/total*100),r=rating(pct);app.innerHTML=`<section class="card test-card results"><div class="rating-ring" style="--result-angle:${pct*3.6}deg"><strong>${pct}%</strong></div><span class="eyebrow">테스트 완료</span><h1>${total}문제 중 ${s.correct}문제 정답</h1><div class="rating">${r[0]} 등급</div><p>${r[1]}</p><div class="result-stats"><div><strong>${s.correct}</strong><small>정답</small></div><div><strong>${total-s.correct}</strong><small>오답</small></div><div><strong>${score}</strong><small>누적 점수</small></div></div><button class="btn primary" id="retry">다시 도전</button></section>`;document.querySelector('#retry').onclick=()=>startTest(s.type)}
function render(){save();mode==='learn'?renderLearn():testState?renderQuestion():startTest(mode)}
save();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
