const FALLBACK='./images/placeholder-suv.svg',storageKey='car-master-black-known-v1';
const labels={all:'전체',exterior:'외장',interior:'내장',performance:'성능',safety:'안전',other:'기타'};
let items=[],sources={},category='all',index=0,showKnown=false,known=new Set(JSON.parse(localStorage.getItem(storageKey)||'[]'));
const $=id=>document.getElementById(id);
const descriptions={'0001':['A hinged panel that covers the engine compartment.','엔진룸을 덮는 차량 전면 상부의 큰 패널입니다.'],'0002':['The main lights that illuminate the road ahead.','차량 전면 좌우에서 앞길을 비추는 주 조명입니다.'],'0003':['Rubber blades that clear water from the windshield.','앞유리의 물과 이물질을 닦는 고무 블레이드입니다.'],'0004':['Exterior mirrors used to check the side and rear.','차량 옆과 뒤를 확인하는 외부 미러입니다.'],'0007':['Rubber components that contact the road.','노면과 직접 맞닿는 고무 부품입니다.'],'0008':['Metal assemblies mounted inside the tires.','타이어 안쪽에 결합되는 금속 회전 부품입니다.']};
function classify(item){const n=(item.en+' '+item.ko).toUpperCase();if(/AIRBAG|BELT|SENSOR|CAMERA|RADAR/.test(n))return'safety';if(/ENGINE|MOTOR|BATTERY|BRAKE|TRANSMISSION/.test(n))return'performance';if(/SEAT|STEERING|CONSOLE|PAD|SPEAKER|CARGO/.test(n))return'interior';if(/HOOD|LIGHT|WIPER|MIRROR|WINDOW|SUNROOF|TIRE|WHEEL|DOOR|LIFTGATE|BUMPER|GRILLE|SPOILER|ROOF|ANTENNA/.test(n))return'exterior';return'other'}
function imageFor(item){if(item.image)return'./'+item.image;for(const ref of item.source_refs||[]){const s=sources[ref],asset=s?.repo_asset||s?.extracted_assets?.[0]?.repo_asset;if(asset)return'./'+asset}if(['0001','0002','0003','0009','0010'].includes(item.id))return'./images/venue/front.jpg';if(['0004','0005','0006','0007','0008'].includes(item.id))return'./images/venue/side.jpg';return FALLBACK}
function visible(){return items.filter(x=>(category==='all'||x.category===category)&&(showKnown||!known.has(x.id)))}
function rank(p){if(p>=80)return['Maestro · 마에스트로','자동차를 읽는 눈이 생겼군요. 마지막 디테일까지!'];if(p>=60)return['Expert · 엑스퍼트','상당한 실력이에요. 남은 용어도 정복해 보세요!'];if(p>=40)return['Specialist · 스페셜리스트','이제 절반이 가까워졌어요. 디테일까지 살펴보세요.'];if(p>=20)return['Explorer · 익스플로러','익숙한 부품이 늘고 있어요. 좋은 출발입니다!'];return['Beginner · 비기너','하나씩 알아가는 순간, 자동차가 다르게 보입니다.']}
function renderTabs(){const cats=['all','exterior','interior','performance','safety','other'];$('tabs').innerHTML=cats.map(c=>`<button class="tab ${c===category?'active':''}" data-category="${c}" type="button">${labels[c]}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{category=b.dataset.category;index=0;render()})}
function fitText(element,minSize){element.style.fontSize='';let size=parseFloat(getComputedStyle(element).fontSize);while(element.scrollHeight>element.clientHeight&&size>minSize){size-=.5;element.style.fontSize=size+'px'}}
function fitCardCopy(){fitText($('term'),16);fitText($('descriptionEn'),9.5);fitText($('descriptionKo'),9.5)}
function render(){renderTabs();const list=visible(),pct=items.length?Math.round(known.size/items.length*100):0,[r]=rank(pct);$('rankName').textContent=r;$('knownCount').textContent=`${known.size} / ${items.length} · ${pct}%`;$('progressBar').style.width=pct+'%';$('restore').textContent='숨긴 카드 복원';if(!list.length){$('position').textContent='0 / 0';$('card').innerHTML='<div class="empty">이 그룹의 카드를 모두 학습했습니다.</div>';$('know').disabled=true;return}$('know').disabled=false;index=(index+list.length)%list.length;const p=list[index],d=descriptions[p.id]||[`Learn to recognize the ${p.en.toLowerCase()} by its shape and location.`,`${p.ko}의 형태와 장착 위치를 사진으로 익혀보세요.`];$('position').textContent=`${index+1} / ${list.length}`;$('itemId').textContent=p.id;$('term').textContent=p.en;$('alias').textContent=p.alias?`(${p.alias})`:'';$('ko').textContent=p.ko;$('descriptionEn').textContent=d[0];$('descriptionKo').textContent=d[1];fitCardCopy();const img=$('partImage');img.alt=`${p.ko} · ${p.en}`;img.src=imageFor(p);img.onerror=()=>{img.onerror=null;img.src=FALLBACK}}
function move(delta){index+=delta;render()}function notify(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2400)}
let touchStart=null;
let autoplayTimer=null;
function toggleAutoplay(){const button=$('autoplay');if(autoplayTimer){clearInterval(autoplayTimer);autoplayTimer=null;button.textContent='▶ AUTO';button.setAttribute('aria-pressed','false')}else{autoplayTimer=setInterval(()=>move(1),3000);button.textContent='Ⅱ AUTO';button.setAttribute('aria-pressed','true')}}
function startSwipe(event){const touch=event.changedTouches[0];touchStart={x:touch.clientX,y:touch.clientY}}
function endSwipe(event){if(!touchStart)return;const touch=event.changedTouches[0],dx=touch.clientX-touchStart.x,dy=touch.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>=45&&Math.abs(dx)>Math.abs(dy)*1.25)move(dx<0?1:-1)}
$('card').addEventListener('touchstart',startSwipe,{passive:true});
$('card').addEventListener('touchend',endSwipe,{passive:true});
$('autoplay').onclick=toggleAutoplay;
document.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')move(-1);if(event.key==='ArrowRight')move(1)});
$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('restore').onclick=()=>{if(!known.size){notify('복원할 숨긴 카드가 없습니다.');return}known.clear();localStorage.removeItem(storageKey);location.reload()};$('know').onclick=()=>{const list=visible();if(!list.length)return;const before=rank(Math.round(known.size/items.length*100))[0];known.add(list[index].id);localStorage.setItem(storageKey,JSON.stringify([...known]));const after=rank(Math.round(known.size/items.length*100));if(before!==after[0])notify(after[1]);render()};
Promise.all([fetch('./data/master.json').then(r=>r.json()),fetch('./data/source_registry.json').then(r=>r.json())]).then(([master,registry])=>{sources=registry.sources||{};items=master.items.filter(x=>x.status==='PASS'&&!x.production_backlog).map(x=>({...x,category:classify(x)}));render()}).catch(()=>{$('card').innerHTML='<div class="empty">데이터를 불러오지 못했습니다.<br>잠시 후 다시 시도해 주세요.</div>'});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));
