const $=id=>document.getElementById(id),STORE='carVocabKnown',TOTAL_TEST=20;
let items=[],stepGroups=[],index=0,currentStep=Number(localStorage.currentStep||1),completedSteps=JSON.parse(localStorage.completedSteps||'[]'),known=new Set(JSON.parse(localStorage.getItem(STORE)||'[]')),testUnlocked=localStorage.testUnlocked==='true',testPassed=localStorage.testPassed==='true',inventoryKey=localStorage.inventoryKey==='true',inventoryUnlocked=localStorage.inventoryUnlocked==='true',coffeeReward=Number(localStorage.coffeeReward||0),rewardClaimed=localStorage.rewardClaimed==='true',testQuestions=[],testIndex=0,testResults=[],reviewReturn=false,autoplayTimer=null,touchStart=null;
const views=['learnView','testView','resultView','inventoryView'];
function save(){localStorage.currentStep=currentStep;localStorage.completedSteps=JSON.stringify(completedSteps);localStorage.setItem(STORE,JSON.stringify([...known]));localStorage.testUnlocked=testUnlocked;localStorage.testPassed=testPassed;localStorage.inventoryKey=inventoryKey;localStorage.inventoryUnlocked=inventoryUnlocked;localStorage.coffeeReward=coffeeReward;localStorage.rewardClaimed=rewardClaimed}
function fit(el,min){el.style.fontSize='';let n=parseFloat(getComputedStyle(el).fontSize);while(el.scrollHeight>el.clientHeight&&n>min){n-=.5;el.style.fontSize=n+'px'}}
function image(item){return './'+item.image}
function applyImageLayout(img,item){
  const box=img?.parentElement,isVehicle=item?.view==='vehicle';
  img?.classList.toggle('vehicle-image',isVehicle);
  box?.classList.toggle('vehicle-visual',isVehicle);
  if(!img)return;
  img.style.objectPosition=item?.object_position||'50% 50%';
  if(isVehicle){
    const kind=(item.vehicle_type||'passenger').toLowerCase();
    img.dataset.vehicleType=kind;
  }else{
    delete img.dataset.vehicleType;
  }
}
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));renderJourney()}
function stepFor(id){return stepGroups.findIndex(g=>g.some(x=>x.id===id))+1}
function remainingInStep(step=currentStep){return (stepGroups[step-1]||[]).filter(x=>!known.has(x.id))}
function renderJourney(){const nodes=[1,2,3,4,5,'TEST','INVENTORY'];$('journey').innerHTML=nodes.map(n=>{let done,current,locked=false;if(typeof n==='number'){done=completedSteps.includes(n);current=!done&&currentStep===n}else if(n==='TEST'){done=testPassed;current=!done&&!$('testView').classList.contains('hidden');locked=!testUnlocked}else{done=rewardClaimed;current=!$('inventoryView').classList.contains('hidden');locked=!inventoryUnlocked}return `<button type="button" data-node="${n}" class="${done?'done ':''}${current?'current ':''}${locked?'locked':''}">${typeof n==='number'?'STEP '+n:n}${done?' ✓':''}</button>`}).join('');document.querySelectorAll('#journey button').forEach(b=>b.onclick=()=>navigate(b.dataset.node));const done=completedSteps.length;$('journeyText').textContent=testUnlocked?'5 / 5 단계 완료 · 시험 자격 획득':`${done} / 5 단계 완료 · 시험까지 ${5-done}단계 남았습니다`}
function navigate(node){if(/^\d$/.test(node)){currentStep=Number(node);index=0;save();showView('learnView');renderLearn();return}if(node==='TEST'){if(!testUnlocked){toast('5단계를 먼저 완료하세요.');return}startTest();return}showInventory()}
function renderLearn(forced){showView('learnView');const list=forced?[forced]:remainingInStep();if(!list.length){if(currentStep<=5)completeStep();return}index=(index+list.length)%list.length;const p=list[index],en=`Learn to recognize the ${p.en.toLowerCase()} by its shape and location.`,ko=`${p.ko}의 형태와 장착 위치를 사진으로 익혀보세요.`;$('position').textContent=`${index+1} / ${list.length} · STEP ${Math.min(currentStep,5)}`;$('itemId').textContent=p.id;$('term').textContent=p.en;$('alias').textContent=p.alias?`(${Array.isArray(p.alias)?p.alias.join(' · '):p.alias})`:'';$('descriptionEn').textContent=en;$('descriptionKo').textContent=ko;$('partImage').src=image(p);$('partImage').alt=`${p.en} 학습 이미지`;applyImageLayout($('partImage'),p);fit($('term'),15);fit($('descriptionEn'),9);fit($('descriptionKo'),9);$('know').classList.toggle('hidden',!!forced);$('returnResult').classList.toggle('hidden',!forced);if(forced){$('card').classList.remove('highlight');requestAnimationFrame(()=>$('card').classList.add('highlight'));setTimeout(()=>$('card').scrollIntoView({behavior:'smooth',block:'center'}),50)}renderJourney()}
function markKnown(){const list=remainingInStep();if(!list.length)return;known.add(list[index].id);save();const learned=known.size;if(learned%10===0){const cheers=['좋아요! 차를 보는 눈이 자라고 있어요.','NICE! 벌써 '+learned+'개를 익혔어요.','PERFECT! 커피 보상까지 계속 달려요.','잘하고 있어요! 다음 부품도 확인해 볼까요?'];toast(cheers[Math.floor(learned/10)%cheers.length])}renderLearn()}
function completeStep(){const isNew=!completedSteps.includes(currentStep);if(isNew){completedSteps.push(currentStep);coffeeReward=Math.max(coffeeReward,completedSteps.length)}const cleared=currentStep;if(currentStep<5){currentStep++;index=0;save();flash(`STEP ${cleared} CLEAR`,`커피 1잔 적재 · 현재 ${coffeeReward}/5잔 · 시험까지 ${5-completedSteps.length}단계`,()=>renderLearn());return}testUnlocked=true;currentStep=5;save();flash('STEP 5 CLEAR','커피 1잔 적재 · 현재 5/5잔 · 인벤토리 적재 완료',()=>flash('TEST UNLOCKED','시험 자격을 획득했습니다',startTest,'시험 응시하기'),'계속하기')}
function flash(main,sub,action,label){$('celebrateTop').textContent=main.includes('STEP')?'STAGE CLEAR':'CAR VOCABULARY';$('celebrateMain').textContent=main;$('celebrateSub').textContent=sub;const btn=$('celebrateAction');btn.classList.toggle('hidden',!action);btn.textContent=label||'계속하기';btn.onclick=()=>{$('celebrate').classList.add('hidden');action?.()};$('celebrate').classList.remove('hidden');if(!action)setTimeout(()=>$('celebrate').classList.add('hidden'),950)}
function shuffle(source){const a=[...source];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startTest(){if(!testUnlocked)return;testQuestions=shuffle(items).slice(0,TOTAL_TEST);testIndex=0;testResults=[];reviewReturn=false;showView('testView');renderTest()}
function renderTest(){const q=testQuestions[testIndex];$('testCount').textContent=`TEST ${String(testIndex+1).padStart(2,'0')} / ${TOTAL_TEST}`;$('testImage').src=image(q);applyImageLayout($('testImage'),q);$('answer').value='';$('answer').focus()}
function normalize(s){return s.trim().toLocaleUpperCase('en-US')}
function primaryAnswer(en){return en.replace(/\s*\([^()]+\)\s*$/,'').trim()}
function submitAnswer(e){e.preventDefault();const q=testQuestions[testIndex],answer=$('answer').value,correct=normalize(answer)===normalize(primaryAnswer(q.en));testResults.push({item:q,answer,correct});testIndex++;if(testIndex<TOTAL_TEST)renderTest();else finishTest()}
function finishTest(){const score=testResults.filter(x=>x.correct).length,passed=score===TOTAL_TEST;if(passed){testPassed=true;inventoryKey=true;save();flash('PASS',`${score} / ${TOTAL_TEST}`,()=>keyAcquired());return}showResults(score)}
function keyAcquired(){$('celebrateTop').textContent='PASS · 20 / 20';$('celebrateMain').textContent='KEY';$('celebrateSub').textContent='KEY ACQUIRED · 인벤토리 열쇠를 획득했습니다';const b=$('celebrateAction');b.textContent='인벤토리 열기';b.classList.remove('hidden');b.onclick=()=>{inventoryUnlocked=true;inventoryKey=false;save();$('celebrate').classList.add('hidden');showInventory()};$('celebrate').classList.remove('hidden')}
function showResults(score=testResults.filter(x=>x.correct).length){showView('resultView');const wrong=testResults.filter(x=>!x.correct);$('resultBody').innerHTML=`<div class="result-score"><span>TEST RESULT</span><strong>${score} / ${TOTAL_TEST}</strong><h2>${score===TOTAL_TEST?'PASS':'조금만 더!'}</h2><p>${wrong.length} Incorrect · 학습 내용을 확인하고 재도전해보세요.</p></div><div class="wrong-list">${wrong.map(x=>`<div class="wrong-item"><img src="${image(x.item)}" alt=""><div><strong>${x.item.en}</strong><span>입력: ${x.answer||'—'}</span></div><button type="button" data-review="${x.item.id}">학습 카드 보기</button></div>`).join('')}</div><button id="retry" class="primary" type="button">다시 시험보기</button><button id="backLearn" class="secondary" type="button">학습으로 돌아가기</button>`;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewCard(b.dataset.review));$('retry').onclick=startTest;$('backLearn').onclick=()=>{currentStep=1;renderLearn()}}
function reviewCard(id){const item=items.find(x=>x.id===id);if(!item)return;reviewReturn=true;currentStep=stepFor(id);renderLearn(item)}
function renderCoffeeStack(){const cups=Array.from({length:coffeeReward},(_,i)=>`<img src="./images/rewards/mega-americano.jpg" alt="적재된 커피 ${i+1}잔">`).join('');['coffeeStack','lockedCoffeeStack'].forEach(id=>{const stack=$(id);if(stack)stack.innerHTML=cups})}function showInventory(){showView('inventoryView');$('inventoryLocked').classList.toggle('hidden',inventoryUnlocked);$('inventoryOpen').classList.toggle('hidden',!inventoryUnlocked);$('storedCoffee').textContent=`${coffeeReward} / 5`;renderCoffeeStack();if(inventoryUnlocked){$('rewardStatus').textContent=rewardClaimed?'RECEIVED':'AVAILABLE';$('claim').textContent=rewardClaimed?'수령 완료':'수령하기';$('claim').disabled=rewardClaimed}}
function claimReward(){rewardClaimed=true;save();showInventory();flash('RECEIVED','아이스아메리카노 5잔을 수령했습니다')}
function move(n){const list=remainingInStep();if(!list.length)return;index=(index+n+list.length)%list.length;renderLearn()}
function toggleAuto(){const b=$('autoplay');if(autoplayTimer){clearInterval(autoplayTimer);autoplayTimer=null;b.textContent='▶ AUTO';b.setAttribute('aria-pressed','false')}else{autoplayTimer=setInterval(()=>move(1),3000);b.textContent='Ⅱ AUTO';b.setAttribute('aria-pressed','true')}}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function restore(){if(!known.size){toast('복원할 숨긴 카드가 없습니다.');return}known.clear();currentStep=1;index=0;save();renderLearn();toast('숨긴 카드를 모두 복원했습니다.')}
function resetAll(){if(!confirm('학습, 시험, 보상 진행을 모두 초기화할까요?'))return;['currentStep','completedSteps','testUnlocked','testPassed','inventoryKey','inventoryUnlocked','coffeeReward','rewardClaimed',STORE,'carVocabIntroSeen'].forEach(k=>localStorage.removeItem(k));location.reload()}
$('answerForm').onsubmit=submitAnswer;$('know').onclick=markKnown;$('restore').onclick=restore;$('autoplay').onclick=toggleAuto;$('prevCard').onclick=()=>move(-1);$('nextCard').onclick=()=>move(1);$('returnResult').onclick=()=>showResults();$('claim').onclick=claimReward;$('reset').onclick=resetAll;$('gameRules').onclick=()=>{$('start').textContent='확인';$('introOverlay').classList.remove('hidden')};$('start').onclick=()=>{localStorage.carVocabIntroSeen='true';$('introOverlay').classList.add('hidden')};document.addEventListener('keydown',e=>{if(!$('learnView').classList.contains('hidden')&&e.key==='ArrowLeft')move(-1);if(!$('learnView').classList.contains('hidden')&&e.key==='ArrowRight')move(1)});$('card').addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});$('card').addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.2)move(dx<0?1:-1)},{passive:true});
fetch('./data/master.json').then(r=>r.json()).then(master=>{items=master.items.filter(x=>x.status==='PASS'&&!x.production_backlog&&x.image);const size=Math.ceil(items.length/5);stepGroups=Array.from({length:5},(_,i)=>items.slice(i*size,Math.min((i+1)*size,items.length)));if(!localStorage.carVocabIntroSeen)$('introOverlay').classList.remove('hidden');if(testPassed&&inventoryUnlocked)showInventory();else renderLearn()}).catch(()=>toast('데이터를 불러오지 못했습니다.'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));
