from pathlib import Path
from PIL import Image, ImageOps, ImageDraw
import math, urllib.request

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "images" / "source"
OUT = ROOT / "production-preview"
PARTS = ROOT / "images" / "parts"
OUT.mkdir(exist_ok=True)
PARTS.mkdir(parents=True, exist_ok=True)

specs = {
    "0011": (SRC/"HY_LX3_2026_REAR_OVERVIEW/1C_OutsideVehicleRearOverview.jpg.png", (0.08,0.30,0.48,0.72), "PASS", "door panel + seams + handle"),
    "0012": (SRC/"HY_LX3_2026_FUEL_DOOR/2C_FuelInletDoor.jpg.png", (0.20,0.06,0.92,0.94), "PASS", "fuel filler door"),
    "0013": (SRC/"HY_IONIQ5_IN_OFFICIAL_PDF/2C_HowToUseChargingDoor.jpg.png", (0.00,0.02,0.66,0.88), "PASS", "charging door/flap"),
    "0014": (SRC/"HY_NX4A_2026_REAR_LAMP/2C_RearLampOverview.jpg.png", (0.12,0.00,0.88,0.72), "PASS", "complete rear lamp housing"),
    "0015": (SRC/"HY_MX5A_2024_REVERSE/2C_BackupLampChange2.jpg.png", (0.08,0.05,0.90,0.92), "PASS", "backup lamp unit + connector"),
    "0016": (SRC/"HY_LX3_2026_REAR_OVERVIEW/1C_OutsideVehicleRearOverview.jpg.png", (0.43,0.22,0.94,0.80), "PASS", "liftgate perimeter + rear glass + lower edge"),
    "0018": (SRC/"HY_LX3_2026_ANTENNA/2C_Antenna.jpg.png", (0.58,0.20,0.94,0.68), "PASS", "roof shark-fin antenna"),
    "0019": (SRC/"HY_LX2_2025_REAR_WIPER/B0452KO05.eps.png", (0.00,0.02,0.72,0.92), "PASS", "rear wiper blade + arm"),
    "0020": (SRC/"HY_NX4_2025_HIGH_STOP/2C_HighMountedStopLamp.jpg.png", (0.12,0.00,0.88,0.74), "PASS", "high mounted stop lamp + spoiler context"),
}

def crop_norm(im, b):
    w,h=im.size
    x1,y1,x2,y2 = [max(0,min(1,v)) for v in b]
    c=im.crop((int(w*x1),int(h*y1),int(w*x2),int(h*y2)))
    cw,ch=c.size
    if cw/ch > 4/3:
        nw=int(ch*4/3); x=(cw-nw)//2; c=c.crop((x,0,x+nw,ch))
    else:
        nh=int(cw*3/4); y=(ch-nh)//2; c=c.crop((0,y,cw,y+nh))
    return c

cards=[]
report=["# 0011–0020 Chat crop QA","",
        "Generated by Chat production pipeline. Production progress is unchanged until live BLACK UI verification.",
        "",
        "| ID | QA | Physical recognition target |",
        "|---|---|---|"]
for id_, (p,b,status,note) in specs.items():
    im=Image.open(p).convert("RGB")
    c=crop_norm(im,b)
    preview=OUT/f"{id_}.jpg"
    final=PARTS/f"{id_}.jpg"
    c.save(preview,quality=94,subsampling=0)
    c.save(final,quality=94,subsampling=0)
    report.append(f"| {id_} | {status} | {note} |")

    thumb=ImageOps.contain(c,(520,390))
    card=Image.new("RGB",(560,460),"white")
    card.paste(thumb,((560-thumb.width)//2,10))
    d=ImageDraw.Draw(card)
    d.text((12,410),f"{id_} {status} — {note}",fill="black")
    d.text((12,432),f"source: {p.name} | crop: {c.size[0]}x{c.size[1]}",fill="black")
    cards.append(card)

report += ["",
"## 0017 — REVIEW",
"- Existing official AXEV overview identifies camera location with a callout, but the physical lens/module is not visually unmistakable enough for a learning card.",
"- Do not replace 0017 with the current broad crop.",
"- Find a stronger Hyundai official close-up where the rear camera lens/module itself can be recognized without reading the title.",
"- Keep Production progress unchanged.",
]
(ROOT/"research"/"0011-0020-chat-crop-qa.md").write_text("\n".join(report)+"\n",encoding="utf-8")

cols=2; rows=math.ceil(len(cards)/cols)
sheet=Image.new("RGB",(cols*560,rows*460),"white")
for i,c in enumerate(cards):
    sheet.paste(c,((i%cols)*560,(i//cols)*460))
sheet.save(OUT/"0011-0020-candidates.jpg",quality=91)
print("generated",len(cards),"final crop candidates; 0017 held REVIEW")
